apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: access-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: access-operator
    app.kubernetes.io/part-of: rhoai-platform
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/dandawg/rhoai-deploy.git
    targetRevision: main
    path: platform/access/eso-operator
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
