apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-minio-secret-reader
  namespace: minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-minio-secret-reader
subjects:
  - kind: ServiceAccount
    name: eso-minio-reader
    namespace: external-secrets-operator
